### ISSUE TITLE
初始化客户端报错 KeyError: 'Client'

### ISSUE THREAD

**Issue by StirrerCymbal5zn** [XYenon/efb-qq-plugin-go-cqhttp#14]
从端是go-cqhttp并配置完成，启动go-cqhttp没有问题且可以正常接收群消息，错误日志如下
guys@guys-virtual-machine:~/.ehforwarderbot/profiles/default$ ehforwarderbot
2021-10-14 11:17:17,425 [Level 99]: ehforwarderbot.main (main.init; main.py:129)
正在初始化从端 milkice.qq#default…
Traceback (most recent call last):
File "/usr/local/bin/ehforwarderbot", line 8, in
sys.exit(main())
File "/usr/local/lib/python3.8/dist-packages/ehforwarderbot/main.py", line 335, in main
init(conf)
File "/usr/local/lib/python3.8/dist-packages/ehforwarderbot/main.py", line 135, in init
coordinator.add_channel(cls(instance_id=instance_id))
File "/usr/local/lib/python3.8/dist-packages/efb_qq_slave/init.py", line 44, in init
self.init_client_manager()
File "/usr/local/lib/python3.8/dist-packages/efb_qq_slave/init.py", line 73, in init_client_manager
self.QQClientMgr = ClientMgr(self.config['Client'], self.config, self)
KeyError: 'Client'

python3.9版本，唯独最后一步启动EFB出错了

**Comment by StirrerCymbal5zn** [comment]
> 可能是没读到配置文件，带 `--verbose` 启动看看日志呢

似乎是一样的：
guys@guys-virtual-machine:~/Desktop$ ehforwarderbot --verbose
2021-10-23 09:17:16,149 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:129)
     正在初始化从端 milkice.qq#default… 
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/ehforwarderbot/__main__.py", line 335, in main
    init(conf)
  File "/usr/local/lib/python3.8/dist-packages/ehforwarderbot/__main__.py", line 135, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.8/dist-packages/efb_qq_slave/__init__.py", line 44, in __init__
    self.init_client_manager()
  File "/usr/local/lib/python3.8/dist-packages/efb_qq_slave/__init__.py", line 73, in init_client_manager
    self.QQClientMgr = ClientMgr(self.config['Client'], self.config, self)
KeyError: 'Client'


这是版本号：
guys@guys-virtual-machine:~/.ehforwarderbot/profiles/default/milkice.qq$ ehforwarderbot -V
EH Forwarder Bot
版本: 2.1.1
Python 版本:
3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0]
正在使用配置文件「default」。

主端:
    Telegram Master (blueset.telegram) 2.2.4 # 默认实例

从端:
    QQ Slave (milkice.qq) 2.0.1-dev # default

中间件:
    尚未启用任何中间件。
