### ISSUE TITLE
最新版本 go-cqhttp 會導致無法啓動

### ISSUE THREAD

**Issue by AkazaRenn** [XYenon/efb-qq-plugin-go-cqhttp#16]
```
[01/Dec/2021:04:57:44] ENGINE Bus STARTING
[01/Dec/2021:04:57:44] ENGINE Started monitor thread 'Autoreloader'.
[01/Dec/2021:04:57:44] ENGINE Serving on http://127.0.0.1:8000
[01/Dec/2021:04:57:44] ENGINE Bus STARTED
2021-12-01 04:57:44,736 [ERROR]: cqhttp (app.log_exception; app.py:1891)
    Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/cqhttp/__init__.py", line 91, in _handle
    type_ = event.get('post_type', '')
AttributeError: 'NoneType' object has no attribute 'get'
```

用的 go-cqhttp 模式，以下是配置文件：
```yaml
Client: GoCQHttp                         # 指定要使用的 QQ 客户端（此处为CoolQ）
GoCQHttp:
  type: HTTP                        # 指定 efb-qq-plugin-go-cqhttp 与 GoCQHttp 通信的方式 现阶段仅支持 HTTP
  access_token: ############################
  api_root: http://127.0.0.1:5700/  # GoCQHttp API接口地址/端口
  host: 127.0.0.1                   # efb-qq-slave 所监听的地址用于接收消息
  port: 8000                        # 同上
```

報錯的 go-cqhttp 版本是 https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-beta8-fix1
測試可用的版本是 https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-beta3

**Comment by AkazaRenn** [comment]
不過 beta8 是開發者預覽版所以也未必是這邊的問題，如果不是的話就很不好意思，麻煩您直接關閉就好了。

**Comment by CKylinMC** [comment]
一样的问题。

**Comment by CKylinMC** [comment]
> go-cqhttp_1.0.0-beta8-fix2_linux_amd64.rpm

更新到fix2已正常，感谢

**Comment by CKylinMC** [comment]
> go-cqhttp_1.0.0-beta8-fix2_linux_amd64.rpm

更新到fix2已正常，感谢

**Comment by AkazaRenn** [comment]
我也是更新到 fix2 之後正常
