### ISSUE TITLE
不支持回覆的消息

### ISSUE THREAD

**Issue by AkazaRenn** [XYenon/efb-qq-plugin-go-cqhttp#8]
QQ 上收到「回覆」類型的消息（手機 QQ 上通過長按消息選擇「回覆」）會被直接無視掉，有點影響聊天。不知道做成對應的 EFB 式的回覆難度如何，但是簡化一下只是內容發出來的話應該不會有很大工作量。

**Comment by XYenon** [comment]
应该已经支持了吧，看看版本是不是最新的 2.0.8

**Comment by AkazaRenn** [comment]
> 应该已经支持了吧，看看版本是不是最新的 2.0.8

是 EQS 的版本還是這個插件的版本？EQS 是 2.0.1，我看好像沒有新的 release，這個插件是從 GitHub 裝的應該也沒有版本號吧

**Comment by AkazaRenn** [comment]
> 应该已经支持了吧，看看版本是不是最新的 2.0.8

剛剛更新了一下，好像還是不行

**Comment by XYenon** [comment]
看看日志里有没有报错之类的呢

**Comment by AkazaRenn** [comment]
> 看看日志里有没有报错之类的呢

```
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]: 2021-08-03 18:15:58,347 [ERROR]: cqhttp (app.log_exception; app.py:1891)
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:     Exception on / [POST]
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]: Traceback (most recent call last):
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:     response = self.full_dispatch_request()
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:     rv = self.handle_user_exception(e)
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:     reraise(exc_type, exc_value, tb)
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:   File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:     raise value
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:     rv = self.dispatch_request()
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:     return self.view_functions[rule.endpoint](**req.view_args)
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:   File "/usr/local/lib/python3.8/dist-packages/cqhttp/__init__.py", line 101, in _handle
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:     response = handler(event)
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:   File "/usr/local/lib/python3.8/dist-packages/cqhttp/__init__.py", line 37, in wrapper
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:     return func(*args, **kwargs)
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:   File "/usr/local/lib/python3.8/dist-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 178, in handle_msg
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:     main_text, messages, at_dict = message_elements_wrapper(context, msg_elements, chat)
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:   File "/usr/local/lib/python3.8/dist-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 133, in message_elements_wrapper
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:     sub_main_text, sub_messages, sub_at_list = message_element_wrapper(context, msg_element, chat)
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:   File "/usr/local/lib/python3.8/dist-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 120, in message_element_wrapper
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]:     ref_user = self.get_user_info(msg_data['qq'])
Aug 03 18:15:58 Akaza-NL ehforwarderbot[8921]: KeyError: 'qq'
```
應該是這一段沒錯

**Comment by XYenon** [comment]
检查下 go-cqhttp 的配置有没有按照 README 中配置 `extra-reply-data: true`

**Comment by AkazaRenn** [comment]
> 检查下 go-cqhttp 的配置有没有按照 README 中配置 `extra-reply-data: true`

噢有了，感謝！
